# Production configuration for docker-compose
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: '3.8'

services:
  # Production Airflow configurations
  airflow-webserver:
    image: custom-airflow:latest  # Use pre-built image in production
    restart: unless-stopped
    environment:
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=false
      - AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE=false
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  airflow-scheduler:
    image: custom-airflow:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  airflow-worker:
    image: custom-airflow:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

  # Production database configurations
  postgres:
    restart: unless-stopped
    environment:
      - POSTGRES_SHARED_PRELOAD_LIBRARIES=pg_stat_statements
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  mysql:
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=1G
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  redis:
    restart: unless-stopped
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # Big data services with resource limits
  namenode:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  datanode:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  spark-master:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  spark-worker:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'

  hive-metastore:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'