# Order Status Mapping Configuration
# 用于DWD Orders Pipeline的状态标准化

order_status_mapping:
  # 中文状态映射
  '待确认': 'Pending'
  '待处理': 'Pending'
  '已确认': 'Confirmed'
  '配送中': 'Shipping'
  '已发货': 'Shipped'
  '已完成': 'Delivered'
  '已取消': 'Cancelled'
  
  # 英文状态映射（保持一致性）
  'Pending': 'Pending'
  'Confirmed': 'Confirmed'
  'Shipping': 'Shipping'
  'Shipped': 'Shipped'
  'Delivered': 'Delivered'
  'Cancelled': 'Cancelled'
  
  # 其他可能的状态
  'Processing': 'Confirmed'
  'In Transit': 'Shipping'
  'Completed': 'Delivered'
  'Canceled': 'Cancelled'

payment_status_mapping:
  # 中文支付状态映射
  '未支付': 'Unpaid'
  '已支付': 'Paid'
  '部分支付': 'Partial'
  '已退款': 'Refunded'
  
  # 英文支付状态映射
  'Unpaid': 'Unpaid'
  'Paid': 'Paid'
  'Partial': 'Partial'
  'Refunded': 'Refunded'
  
  # 其他可能的状态
  'Pending Payment': 'Unpaid'
  'Payment Received': 'Paid'
  'Partially Paid': 'Partial'
  'Refund Processed': 'Refunded'

# 数据质量规则
data_quality_rules:
  required_fields:
    - OrderID
    - CustomerID
    - OrderDate
    - OrderStatus
    - TotalAmount
  
  validation_rules:
    min_amount: 0
    max_lead_time_days: 365
    valid_statuses:
      - Pending
      - Confirmed
      - Shipping
      - Shipped
      - Delivered
      - Cancelled