mysql:
  url: jdbc:mysql://10.0.19.6:3306/wudeli
  user: root
  password: Sp1derman123@
  driver: com.mysql.cj.jdbc.Driver

tables:
  - mysql_table: Orders
    hive_table: ods.Orders
    incremental_column: UpdatedDate
    partition_column: dt
    sync_mode: incremental       # 可选值: full, incremental
    enabled: true

  - mysql_table: Customers
    hive_table: ods.Customers
    incremental_column: UpdatedDate
    partition_column: dt
    sync_mode: incremental
    enabled: true

  - mysql_table: Products
    hive_table: ods.Products
    incremental_column: UpdatedDate
    partition_column: dt
    sync_mode: incremental
    enabled: true

  - mysql_table: OrderDetails
    hive_table: ods.OrderDetails
    incremental_column: UpdatedDate
    partition_column: dt
    sync_mode: incremental
    enabled: true
    
  - mysql_table: Warehouses
    hive_table: ods.Warehouses
    incremental_column: UpdatedDate
    partition_column: dt
    sync_mode: incremental
    enabled: true

  - mysql_table: Employees
    hive_table: ods.Employees
    incremental_column: UpdatedDate
    partition_column: dt
    sync_mode: full
    enabled: true

  - mysql_table: Factories
    hive_table: ods.Factories
    incremental_column: UpdatedDate
    partition_column: dt
    sync_mode: full
    enabled: true

  - mysql_table: Inventory
    hive_table: ods.Inventory
    incremental_column: UpdatedDate
    partition_column: dt
    sync_mode: full
    enabled: true
  
  - mysql_table: InventoryTransactions
    hive_table: ods.InventoryTransactions
    incremental_column: CreatedDate
    partition_column: dt
    sync_mode: full
    enabled: true
  