# 动态ETL配置文件
mysql_conn:
  host: 10.0.19.6
  port: ${MYSQL_PORT:-3306}
  user: ${MYSQL_USER:-root}
  password: ${MYSQL_PASSWORD:-Sp1derman123@}
  database: ${MYSQL_DATABASE:-wudeli}

spark_config:
  master: spark://${SPARK_MASTER_HOST:-spark-master}:${SPARK_MASTER_PORT:-7077}
  deploy_mode: client
  driver_memory: 2g
  executor_memory: ${SPARK_WORKER_MEMORY:-2g}
  executor_cores: ${SPARK_WORKER_CORES:-2}
  num_executors: 2

hdfs_paths:
  base: /user/bigdata/wudeli
  raw: /user/bigdata/wudeli/raw
  processed: /user/bigdata/wudeli/processed
  reports: /user/bigdata/wudeli/reports
  temp: /user/bigdata/wudeli/temp

hive_db: wudeli_analytics

services:
  hdfs_namenode: hdfs://${HDFS_NAMENODE_HOST:-namenode}:${HDFS_NAMENODE_PORT:-9000}
  hive_metastore: thrift://hive-metastore:${HIVE_METASTORE_PORT:-9083}